Email notifications cloud functions (#219)
* use @coindrop.to email addresses. email code is WIP

* wip [skip ci]

* wip [skip ci]

* going to remove emotion, inline styles element not working on gmail

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* change schema to user-based instead of email-list-based

* wip [skip ci]

* wip [skip ci]

* wip. adding react testing library

* working on tests for account settings

* fix lint

* fix lint

* updateUserData is not a function error

* updateUserData is not a function error

* all tests passing so far

* wip [skip ci]

* smaller smartphone mockup on landing page, center for-restaurants text in logo

* update tagline

* fix lint

* add cryptr secret to github actions

* cosmetic changes to landing page

* fix margin on base email template

* wip [skip ci]

* use batch transactions, need to test

* allow user to press enter in confirm email to delete user

* use sendEmail.promise instead of thenning

* getting path error

* getting path error

* deploy to firebase working

* test cloud functions deploy

* commit all files this time

* try to fix Error: Not in a Firebase app directory (could not locate firebase.json)

* try to use default working directory

* ls

* ls

* run ls in same step

* run ls in same step

* add PROJECT_PATH to firebase-action

* clean up yml and eslintrc for firebase functions

* update ignorePatterns on root eslintrc

* exclude src/firebase-functions from root tsc lint

* fix cypress test

* wip [skip ci]

* fix lint

* fix lint

* downgrade react

* fix path of welcome email api method

* send stack trace error

* add logs

* all cryptr inside function

* fix null/undefined error caused by incorrect header name

* cleanup

* rename firebase-functions folder to firebase

* working on testing rules for firestore... kind of a tangent but while im at it...

* firestore rules & test updates. need to test & push in ci

* test firebase rules in ci

* fix tests being run

* fixed UserSettingsPage tests, lots of other progress

* remove test.only

* add test for unsuccessful save. fix lint

* cosmetic updates

* fix UserSettingsPage tests. Update coindrop name regex tests.

* cleanup

* run firebase function tests in ci

* commit changes from root

* run build before test

* specify project in firebase cli for test

* separate firebase tokens for DEV and PROD

* disable firebase functions test & deploy in ci for now

* update email wording